baseURL = 'http://pluviophile225.github.io/'
languageCode = 'en-us'
title = 'pluviophile225'
theme = "hugo-book"

[params]
BookMenuBundle = '/menu'

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/Pluviophile225"
  weight = 10
